#MEMBERS: Shambhavi Mittal and Tanisha Kumar

# -*- coding: utf-8 -*-
"""CS project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16z--PBp1BHan1fDrK5iy_g_2zUho9laP
"""

import nltk
nltk.download('words')

from nltk.corpus import words 
import string
import random

#LEVEL 1
print("WELCOME TO [̲̅s][̲̅u][̲̅b][̲̅s][̲̅c][̲̅r][̲̅a][̲̅b][̲̅b][̲̅l][̲̅e]!\n1.Make words from the 7 random letters given\n2.Type 'P' if you want to pass\n3.If you wish to exit press E(in that case your **oponent wins**)\n4.There are specific points for different letters\nas shown below\n BEST OF LUCK!!") 
print("points for each letter:-\n1 point – A   E   I   O  U   L   N   S   T   R\n2 points – D   G\n3 points – B   C   M   P\n4 points – F   H   V   W   Y\n5 points – K\n8 points – J  X\n10 points – Q  Z")
print()
score_dict={"A":1,"B":3,"C":3,"D":2,"E":1,"F":4,\
       "G":2,"H":4,"I":1,"J":8,"K":5,"L":1,\
       "M":3,"N":1,"O":1,"P":3,"Q":10,"R":1,\
       "S":1,"T":1,"U":1,"V":4,"W":4,"X":8,"Y":4,"Z":10}     #scores

valid_words = words.words()
finalscore1=[]
checkexit=False #To check the exit of the player 

for x in range(2):
  score=0
  cnt=0
  print("PLAYER", x+1)
  print()
  yn=(input("DO YOU WANT TO PLAY?(Y/N) "))
  yesno=yn.upper()
  print()
  while yesno=="Y":
    letters=[]
    cnt+=1
    if cnt==3:
      yesno="N"
    string.ascii_uppercase
    print("USE THE LETTERS GIVEN BELOW TO MAKE A VALID WORD-")
    vowel=["A","E","I","O","U"]

    numC=5                                             # to generate all the letters
    numV=2
    for i in range(numV):
      v=random.randint(0,4)
      letters.append(vowel[v])
    while numC!=0:
      c=random.choice(string.ascii_uppercase)
      if c not in vowel:
        numC-=1
        letters.append(c)
    letter_dict={}
    for a in letters: 
      if a in letter_dict: 
        letter_dict[a] += 1
      else: 
        letter_dict[a] = 1
    print (str(letters)[1:-1])

    word=input("WORD: ")
    word=word.upper()
    if word=="E":                                    #exit 
      print("PLAYER",x+1,"HAS EXITED THE GAME.")
      if x==0:
        print("CONGRATULATIONS PLAYER 2!! YOU WON !!")
      else:
        print("CONGRATULATIONS PLAYER 1!! YOU WON !!")
      checkexit=True
      break
    else:
      if word=="P":                                  #pass
        print("PASS = 0 points") 
        print("Score:", score)
      else: 
        frequencies = {}  
        for char in word: 
          if char in frequencies: 
            frequencies[char] += 1
          else: 
            frequencies[char] = 1

      # check validity of word
      # 1. word contains eligible letters
      # 2. word is a valid english word
        for i in frequencies.keys():
          if i in letter_dict and frequencies[i]<=letter_dict[i]:
            check=True
            continue
          else:
            check=False
            print("OOPS!! INVALID WORD: WORD NOT FORMED USING GIVEN LETTERS")
            print("Score:", score)
            break
        if word.lower() in valid_words and check==True:
          for char in frequencies.keys():
            score+=(score_dict[char]*frequencies[char])
          print("Per character frequency in", word, "is", frequencies)
          print("Score:", score)
        elif word.lower() not in valid_words and check==True:
          print("OOPS!! INVALID WORD: WORD DOES NOT EXIST")
          print("Score:", score)
      print()
  if checkexit==True:
    break  
  print("YOUR CHANCE IS OVER.")
  print()
  finalscore1.append(score)
if checkexit==False:
  print("SCORE OF PLAYER 1:", finalscore1[0])
  print("SCORE OF PLAYER 2:", finalscore1[1])
  if finalscore1[0]> finalscore1[1]:
    print("CONGRATULATIONS PLAYER 1!! YOU WON LEVEL 1!!")
  elif finalscore1[0] == finalscore1[1]:
    print("IT'S A TIE!!")
  else:
    print("CONGRATULATIONS PLAYER 2!! YOU WON LEVEL 1!!")
  print()

#LEVEL 2
  checkexit=False
  print("WELCOME TO LEVEL 2!\n1.Make words from the 7 random letters given\n2.Type 'P' if you want to pass\n3.There are specific points for different letters\nas shown below\n4.If an INVALID WORD  or you PASS(i.e enter 'P') or you make a word from letters other than those given 3 points will be deducted\nBEST OF LUCK!!") # add intro 
  print("points for each letter:-\n1 point – A   E   I   O  U   L   N   S   T   R\n2 points – D   G\n3 points – B   C   M   P\n4 points – F   H   V   W   Y\n5 points – K\n8 points – J  X\n10 points – Q  Z")
  print() 
  finalscore2=[]

  for x in range(2):
    score=0
    cnt=0
    print("PLAYER", x+1)
    print()
    yn=(input("DO YOU WANT TO PLAY?(Y/N) "))
    yesno=yn.upper()
    print()
    while yesno=="Y":
      letters=[]
      cnt+=1
      if cnt==3:
        yesno="N"
      string.ascii_uppercase
      print("USE THE LETTERS GIVEN BELOW TO MAKE A VALID WORD-")
      vowel=["A","E","I","O","U"]

      numC=5
      numV=2
      for i in range(numV):
        v=random.randint(0,4)
        letters.append(vowel[v])
      while numC!=0:
        c=random.choice(string.ascii_uppercase)
        if c not in vowel:
          numC-=1
          letters.append(c)
      letter_dict={}
      for a in letters: 
        if a in letter_dict: 
          letter_dict[a] += 1
        else: 
          letter_dict[a] = 1
      print(str(letters)[1:-1])

      word=input("WORD: ")
      word=word.upper()
      if word=="E":
        print("PLAYER",x+1,"HAS EXITED THE GAME.")
        if x==0:
          print("CONGRATULATIONS PLAYER 2!! YOU WON !!")
        else:
          print("CONGRATULATIONS PLAYER 1!! YOU WON !!")
        checkexit=True
        break
      else:
        if word=="P":
          print("PASS = -3 points") 
          print("New Score:",score,"- 3 =",end=" ")
          score-=3
          print(score)
        else: 
          frequencies = {}  
          for char in word: 
            if char in frequencies: 
              frequencies[char] += 1
            else: 
              frequencies[char] = 1

        # check validity of word

          for i in frequencies.keys():
            if i in letter_dict and frequencies[i]<=letter_dict[i]:
              check=True
              continue
            else:
              check=False
              print("OOPS!! INVALID WORD: WORD NOT FORMED USING GIVEN LETTERS")
              print("New Score:",score,"- 3 =",end=" ")
              score-=3
              print(score)
              break
          if word.lower() in valid_words and check==True:
            for char in frequencies.keys():
              score+=(score_dict[char]*frequencies[char])
            print("Per character frequency in", word, "is", frequencies)
            print("Score:", score)
          elif word.lower() not in valid_words and check==True:
            print("OOPS!! INVALID WORD: WORD DOES NOT EXIST\nINVALID WORD = -3 points")
            print("New Score:",score,"- 3 =",end=" ")
            score-=3
            print(score)
        print()
    if checkexit==True:
      break

    print("YOUR CAHNCE IS OVER.")
    print()
    finalscore2.append(score)
if checkexit==False:
  print("SCORE OF PLAYER 1:", finalscore2[0])
  print("SCORE OF PLAYER 2:", finalscore2[1])
  if finalscore2[0]> finalscore2[1]:
    print("CONGRATULATIONS PLAYER 1!! YOU WON LEVEL 2!!")
  elif finalscore2[0] == finalscore2[1]:
    print("IT'S A TIE!!")
  else:
    print("CONGRATULATIONS PLAYER 2!! YOU WON LEVEL 2!!")
  print()
  print("TOTAL SCORE OF PLAYER 1:" ,finalscore1[0],"+", finalscore2[0],"=",finalscore1[0]+ finalscore2[0])
  print("TOTAL SCORE OF PLAYER 2:" ,finalscore1[1],"+", finalscore2[1],"=",finalscore1[1]+ finalscore2[1])
  if finalscore1[0]+finalscore2[0]>finalscore1[1]+finalscore2[1]:
    print("CONGRATULATIONS PLAYER 1!! YOU WON THE GAME")
  elif finalscore1[0]+finalscore2[0]<finalscore1[1]+finalscore2[1]:
    print("CONGRATULATIONS PLAYER 2!! YOU WON THE GAME!!")
  else:
    print("IT'S A TIE!!")
  print("GAME OVER!")
